export const STATE_DISTRICT_TOWN_DATA = {
  Karnataka: {
    "Bengaluru Urban": [
      "Majestic",
      "Indiranagar",
      "Jayanagar",
      "Koramangala",
      "HSR Layout",
      "Malleshwaram",
      "Whitefield",
      "Marathahalli",
      "Electronic City",
      "Yelahanka",
      "Rajajinagar",
      "Banashankari",
      "BTM Layout",
      "Hebbal",
      "Kengeri",
    ],
    "Bengaluru Rural": [
      "Devanahalli",
      "Doddaballapura",
      "Hoskote",
      "Nelamangala",
    ],
    Mysuru: [
      "Mysuru Town",
      "Kuvempunagara",
      "Sriramapura",
      "Saraswathipuram",
      "Gokulam",
      "V.V. Mohalla",
      "Vijayanagar",
      "Jayalakshmipuram",
      "J.P. Nagar",
      "Nanjangud",
      "Hunsur",
      "T. Narasipura",
      "Periyapatna",
      "K.R. Nagar",
    ],
    "Dakshina Kannada": [
      "Mangaluru",
      "Surathkal",
      "Ullal",
      "Bantwal",
      "Puttur",
      "Belthangady",
      "Sullia",
    ],
    Udupi: ["Udupi Town", "Manipal", "Malpe", "Kundapura", "Karkala", "Kaup"],
    Dharwad: ["Hubballi", "Dharwad Town", "Navalgund", "Kalghatgi"],
    Belagavi: [
      "Belagavi Town",
      "Gokak",
      "Athani",
      "Chikodi",
      "Bailhongal",
      "Saundatti",
      "Ramdurg",
      "Hukkeri",
    ],
    Kalaburagi: ["Kalaburagi Town", "Afzalpur", "Aland", "Chincholi", "Sedam"],
    Ballari: ["Ballari Town", "Kampli", "Siruguppa"],
    Tumakuru: ["Tumakuru Town", "Tiptur", "Kunigal", "Madhugiri", "Sira"],
    Davanagere: ["Davanagere Town", "Harihara", "Honnali", "Channagiri"],
    Shivamogga: [
      "Shivamogga Town",
      "Bhadravati",
      "Sagar",
      "Shikaripura",
      "Soraba",
      "Thirthahalli",
    ],
    Hassan: [
      "Hassan Town",
      "Arsikere",
      "Channarayapatna",
      "Hole Narsipur",
      "Sakleshpur",
    ],
    Chikkamagaluru: [
      "Chikkamagaluru Town",
      "Kadur",
      "Tarikere",
      "Mudigere",
      "Koppa",
    ],
    Kodagu: ["Madikeri", "Virajpet", "Somwarpet", "Kushalnanagar"],
    Mandya: [
      "Mandya Town",
      "Maddur",
      "Malavalli",
      "Pandavapura",
      "Srirangapatna",
      "Nagamangala",
      "K.R. Pet",
    ],
    Ramanagara: ["Ramanagara Town", "Channapatna", "Magadi", "Kanakapura"],
    Chamarajanagar: [
      "Chamarajanagar Town",
      "Kollegal",
      "Gundlupet",
      "Yalandur",
    ],
    "Uttara Kannada": [
      "Karwar",
      "Sirsi",
      "Kumta",
      "Bhatkal",
      "Ankola",
      "Haliyal",
      "Yellapur",
    ],
    Haveri: ["Haveri Town", "Ranebennur", "Byadgi", "Hanagal"],
    Gadag: ["Gadag-Betageri", "Mundargi", "Ron", "Nargund"],
    Bagalkot: ["Bagalkot Town", "Badami", "Jamkhandi", "Mudhol", "Ilkal"],
    Vijayapura: [
      "Vijayapura Town",
      "Indi",
      "Muddebihal",
      "Sindagi",
      "Basavana Bagewadi",
    ],
    Bidar: ["Bidar Town", "Basavakalyan", "Homnabad", "Bhalki", "Aurad"],
    Yadgir: ["Yadgir Town", "Shahapur", "Shorapur"],
    Kolar: [
      "Kolar Town",
      "Kolar Gold Fields (KGF)",
      "Bangarapet",
      "Mulbagal",
      "Srinivaspur",
      "Malur",
    ],
    Chikkaballapur: [
      "Chikkaballapur Town",
      "Chintamani",
      "Sidlaghatta",
      "Gauribidanur",
      "Bagepalli",
    ],
    Chitradurga: [
      "Chitradurga Town",
      "Hiriyur",
      "Challakere",
      "Hosadurga",
      "Holalkere",
      "Molakalmuru",
    ],
    Koppal: ["Koppal Town", "Gangavathi", "Kushtagi", "Yelbarga"],
    Raichur: ["Raichur Town", "Manvi", "Sindhanur", "Lingasugur", "Devadurga"],
  },
  Maharashtra: {
    Mumbai: ["Colaba", "Andheri", "Bandra", "Borivali", "Dadar", "Kurla"],
    Pune: ["Pune City", "Pimpri-Chinchwad", "Hinjewadi", "Kothrud", "Hadapsar"],
    Nagpur: ["Nagpur City", "Kamptee", "Hingna"],
    Nashik: ["Nashik City", "Deolali", "Igatpuri"],
    Aurangabad: ["Aurangabad City", "Paithan", "Sillod"],
    Thane: ["Thane City", "Kalyan", "Dombivli", "Mira-Bhayandar"],
  },
  Delhi: {
    "New Delhi": ["Connaught Place", "Chanakyapuri", "Karol Bagh"],
    "Central Delhi": ["Daryaganj", "Paharganj"],
    "South Delhi": ["Saket", "Hauz Khas", "Mehrauli", "RK Puram"],
    "West Delhi": ["Rajouri Garden", "Punjabi Bagh", "Janakpuri"],
    "North Delhi": ["Civil Lines", "Model Town"],
  },
  Gujarat: {
    Ahmedabad: ["Ahmedabad City", "Maninagar", "Navrangpura"],
    Surat: ["Surat City", "Varachha", "Adajan"],
    Vadodara: ["Vadodara City", "Sayajigunj", "Alkapuri"],
    Rajkot: ["Rajkot City", "Morbi", "Gondal"],
  },
  "Tamil Nadu": {
    Chennai: ["Chennai City", "Adyar", "Anna Nagar", "T-Nagar"],
    Coimbatore: ["Coimbatore City", "Pollachi", "Tiruppur"],
    Madurai: ["Madurai City", "Melur", "Usilampatti"],
  },
  Telangana: {
    Hyderabad: [
      "Hyderabad City",
      "Secunderabad",
      "Gachibowli",
      "Banjara Hills",
    ],
    Warangal: ["Warangal City", "Hanamkonda", "Kazipet"],
    Nizamabad: ["Nizamabad City", "Bodhan", "Armoor"],
  },
  Kerala: {
    Ernakulam: ["Kochi", "Aluva", "Angamaly"],
    Thiruvananthapuram: ["Trivandrum City", "Neyyattinkara", "Attingal"],
    Kozhikode: ["Calicut City", "Vatakara", "Quilandy"],
  },
  "Uttar Pradesh": {
    Lucknow: ["Lucknow City", "Gomti Nagar", "Aliganj"],
    Kanpur: ["Kanpur City", "Jajmau", "Kalyanpur"],
    Agra: ["Agra City", "Tajganj", "Sikandra"],
    Varanasi: ["Varanasi City", "Sarnath", "Ramnagar"],
    Noida: ["Sector 18", "Sector 62", "Greater Noida"],
  },
  "West Bengal": {
    Kolkata: ["Kolkata City", "Salt Lake", "New Town", "Behala"],
    Howrah: ["Howrah City", "Bally", "Uluberia"],
    Darjeeling: ["Darjeeling City", "Siliguri", "Kurseong"],
  },
  Rajasthan: {
    Jaipur: ["Jaipur City", "Amer", "Sanganer"],
    Jodhpur: ["Jodhpur City", "Luni", "Bilara"],
    Udaipur: ["Udaipur City", "Vallabhnagar", "Salumbar"],
  },
  Punjab: {
    Amritsar: ["Amritsar City", "Ajnala", "Baba Bakala"],
    Ludhiana: ["Ludhiana City", "Khanna", "Jagraon"],
    Chandigarh: ["Sector 17", "Sector 35", "Manimajra"],
  },
  Haryana: {
    Gurugram: ["DLF Phase 1", "Cyber Hub", "Sohna Road"],
    Faridabad: ["Nit", "Old Faridabad", "Ballabgarh"],
    Panipat: ["Panipat City", "Samalkha", "Israna"],
  },
  "Madhya Pradesh": {
    Indore: ["Indore City", "Mhow", "Depalpur"],
    Bhopal: ["Bhopal City", "Bairagarh", "Govindpura"],
    Gwalior: ["Gwalior City", "Dabra", "Bhitarwar"],
  },
  "Andhra Pradesh": {
    Visakhapatnam: ["Vizag City", "Gajuwaka", "Anakapalle"],
    Vijayawada: ["Vijayawada City", "Guntupalli", "Kankipadu"],
    Guntur: ["Guntur City", "Tenali", "Narasaraopet"],
  },
  Assam: {
    "Kamrup Metropolitan": ["Guwahati", "Dispur", "Maligaon"],
    Dibrugarh: ["Dibrugarh City", "Chabua", "Naharkatia"],
  },
  Bihar: {
    Patna: ["Patna City", "Danapur", "Phulwari Sharif"],
    Gaya: ["Gaya City", "Bodh Gaya", "Sherghati"],
  },
  Goa: {
    "North Goa": ["Panaji", "Mapusa", "Calangute"],
    "South Goa": ["Margao", "Vasco da Gama", "Ponda"],
  },
  "Himachal Pradesh": {
    Shimla: ["Shimla City", "Rampur", "Rohru"],
    Kullu: ["Kullu Town", "Manali", "Anni"],
  },
  "Jammu and Kashmir": {
    Srinagar: ["Srinagar City", "Ganderbal", "Badgam"],
    Jammu: ["Jammu City", "Akhnoor", "R.S. Pura"],
  },
  Jharkhand: {
    Ranchi: ["Ranchi City", "Hatia", "Kanke"],
    Jamshedpur: ["Tatanagar", "Mango", "Jugsalai"],
  },
  Odisha: {
    Khordha: ["Bhubaneswar", "Khurda Town", "Jatni"],
    Cuttack: ["Cuttack City", "Choudwar", "Athagarh"],
  },
  Uttarakhand: {
    Dehradun: ["Dehradun City", "Mussoorie", "Rishikesh"],
    Nainital: ["Nainital Town", "Haldwani", "Ramnagar"],
  },
  Chhattisgarh: {
    Raipur: ["Raipur City", "Arang", "Abhanpur"],
    Bilaspur: ["Bilaspur City", "Kota", "Takhatpur"],
  },
  Manipur: { "Main Districts": ["Imphal East", "Imphal West"] },
  Meghalaya: { "Main Districts": ["Shillong", "Tura"] },
  Mizoram: { "Main Districts": ["Aizawl", "Lunglei"] },
  Nagaland: { "Main Districts": ["Kohima", "Dimapur"] },
  Sikkim: { "Main Districts": ["Gangtok", "Namchi"] },
  Tripura: { "Main Districts": ["Agartala", "Udaipur"] },
  "Arunachal Pradesh": { "Main Districts": ["Itanagar", "Tawang"] },
  "Andaman and Nicobar Islands": { "Main Districts": ["Port Blair"] },
  Chandigarh: { "Main Districts": ["Chandigarh City"] },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Main Districts": ["Daman", "Diu", "Silvassa"],
  },
  Ladakh: { "Main Districts": ["Leh", "Kargil"] },
  Lakshadweep: { "Main Districts": ["Kavaratti"] },
  Puducherry: {
    "Main Districts": ["Puducherry Town", "Karaikal", "Mahe", "Yanam"],
  },
};
